### ISSUE TITLE
启用灰风mod但是灰风不见了

### ISSUE THREAD

**Issue by 2744735508** [MerCuJerry/stellaris-gray-fix#1]
开局有灰风的信号接入，但是没看到灰风的船，关了所有mod单独启用灰风mod也是只有信号框，但是船模没有显示

**Comment by 2744735508** [comment]
> 开局有灰风的信号接入，但是没看到灰风的船，关了所有mod单独启用灰风mod也是只有信号框，但是船模没有显示

**Comment by MerCuJerry** [comment]
在通讯界面就找得到了
